name: push to lambbda
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: localfiles
        run: ls -la 
      - name: ziping the package
        run: zip -r python.zip python.py
      - name: uploading in lambda
        run: aws lambda update-function-code --function-name  demo --zip-file fileb://python.zip
        env:
          AWS_ACCESS_KEY: ${{secrets.ACCESS_KEY}}
          AWS_SECRET_KEY: ${{secrets.SECRET_KEY}}
          AWS_DEFAULT_REGION: "ap-south-1"
          
