name: push to lambbda
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: localfiles
        run: ls -la 
      - name: checking version 
        run: aws --version
